# Generated by Django 5.1.7 on 2025-08-27 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('airline_name', models.CharField(db_index=True, max_length=100)),
                ('departure_datetime', models.DateTimeField(db_index=True)),
                ('arrival_datetime', models.DateTimeField(db_index=True)),
                ('origin', models.CharField(db_index=True, max_length=10)),
                ('destination', models.CharField(db_index=True, max_length=10)),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True)),
                ('max_cargo_weight', models.PositiveIntegerField(default=10000, help_text='Maximum cargo weight in kg', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_cargo_weight', models.PositiveIntegerField(default=10000, help_text='Available cargo weight in kg', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flights',
                'ordering': ['departure_datetime'],
                'indexes': [models.Index(fields=['origin', 'destination', 'departure_datetime'], name='flights_origin_79a50f_idx'), models.Index(fields=['departure_datetime'], name='flights_departu_c63dbd_idx'), models.Index(fields=['arrival_datetime'], name='flights_arrival_eedb18_idx')],
            },
        ),
    ]
