# Generated by Django 5.1.7 on 2025-08-27 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(db_index=True, help_text='Human-friendly unique reference ID', max_length=20, unique=True)),
                ('origin', models.CharField(db_index=True, max_length=10)),
                ('destination', models.CharField(db_index=True, max_length=10)),
                ('pieces', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='BOOKED', max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', models.CharField(blank=True, max_length=10, null=True)),
                ('flights', models.ManyToManyField(blank=True, related_name='bookings', to='flights.flight')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKED', 'Booked'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('IN_TRANSIT', 'In Transit'), ('DELAYED', 'Delayed'), ('CUSTOM', 'Custom Event')], max_length=20)),
                ('location', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bookings.booking')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.flight')),
            ],
            options={
                'db_table': 'booking_events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['ref_id'], name='bookings_ref_id_2cf627_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_status_8f492c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['origin', 'destination'], name='bookings_origin_9f0262_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_created_118d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingevent',
            index=models.Index(fields=['booking', 'timestamp'], name='booking_eve_booking_fb4365_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='booking_eve_event_t_daac00_idx'),
        ),
    ]
